import type { CompanyTarget } from "../../types";

export const companyTargets: CompanyTarget[] = [
  {
    id: 1,
    name: "삼성전자 DS",
    fit: 88,
    preference: 95,
    status: "서류 제출",
    type: "집중 지원",
    location: "경기도 화성 동탄",
    lat: 37.222,
    lng: 127.107,
    stage: "applied",
    naverPlaceType: "PLACE_POI",
  },
  {
    id: 2,
    name: "SK하이닉스",
    fit: 84,
    preference: 92,
    status: "인적성 예정",
    type: "집중 지원",
    location: "경기도 이천",
    lat: 37.279,
    lng: 127.442,
    stage: "test",
    naverPlaceType: "PLACE_POI",
  },
  {
    id: 3,
    name: "LX세미콘",
    fit: 80,
    preference: 86,
    status: "1차 면접",
    type: "균형 카드",
    location: "서울 서초",
    lat: 37.484,
    lng: 127.035,
    stage: "interview1",
    naverPlaceType: "PLACE_POI",
  },
  {
    id: 4,
    name: "리벨리온",
    fit: 82,
    preference: 90,
    status: "과제 진행 중",
    type: "스트레치",
    location: "경기도 판교",
    lat: 37.401,
    lng: 127.109,
    stage: "test",
    naverPlaceType: "PLACE_POI",
  },
  {
    id: 5,
    name: "텔레칩스",
    fit: 79,
    preference: 76,
    status: "2차 면접",
    type: "균형 카드",
    location: "경기도 판교",
    lat: 37.394,
    lng: 127.112,
    stage: "interview2",
    naverPlaceType: "PLACE_POI",
  },
  {
    id: 6,
    name: "파두",
    fit: 77,
    preference: 74,
    status: "서류 합격",
    type: "안정 카드",
    location: "서울 강남",
    lat: 37.498,
    lng: 127.028,
    stage: "test",
    naverPlaceType: "PLACE_POI",
  },
];
