import type { IndustryNewsItem } from "../../types";

export const industryNews: IndustryNewsItem[] = [
  {
    id: 1,
    title: "AI 반도체 채용에서 검증 중심 포지션 비중이 계속 커지고 있음",
    source: "업계 리서치",
    date: "2026-03-08",
    tag: "AI 반도체",
    summary: "아키텍처 이해와 디버그 오너십을 함께 묻는 공고가 늘고 있습니다.",
    url: "https://example.com/ai-silicon",
  },
  {
    id: 2,
    title: "메모리 기업은 컨트롤러와 인터페이스 깊이를 우선 확인하는 추세",
    source: "업계 리서치",
    date: "2026-03-06",
    tag: "메모리",
    summary: "HBM과 DDR 관련 공고일수록 trade-off 설명 능력이 중요합니다.",
    url: "https://example.com/memory",
  },
  {
    id: 3,
    title: "파운드리 인접 조직은 타이밍과 signoff 기본기를 강하게 확인함",
    source: "업계 리서치",
    date: "2026-03-05",
    tag: "파운드리",
    summary: "기본적인 timing과 signoff 용어를 알고 있으면 인터뷰 초반 흐름을 잡기 쉽습니다.",
    url: "https://example.com/foundry",
  },
  {
    id: 4,
    title: "중견 하드웨어 조직일수록 EDA 자동화와 스크립트 역량 차별화가 큼",
    source: "업계 리서치",
    date: "2026-03-04",
    tag: "EDA 자동화",
    summary: "검증 로그와 파형 자동화 경험이 있으면 사전 선호도가 높습니다.",
    url: "https://example.com/eda",
  },
  {
    id: 5,
    title: "아키텍처 질문은 1차 면접 초반부터 바로 들어오는 추세",
    source: "업계 리서치",
    date: "2026-03-03",
    tag: "아키텍처",
    summary: "파이프라인 처리와 인터페이스 trade-off를 짧게 설명하는 준비가 필요합니다.",
    url: "https://example.com/architecture",
  },
  {
    id: 6,
    title: "차량용 SoC 조직도 공통 인터페이스 이해를 더 강하게 요구하기 시작함",
    source: "업계 리서치",
    date: "2026-03-01",
    tag: "인터페이스",
    summary: "기기군 구분 없이 공통 인터페이스 이해를 묻는 경우가 많아지고 있습니다.",
    url: "https://example.com/interface",
  },
];
